### ISSUE TITLE
maxLength property shows "invalid value" error when given multidigit number

### ISSUE THREAD

**Issue by Zuuja** [jackwootton/json-schema#25] opened 2018-09-10 10:39 UTC
When editing string assertions and min/max length on https://www.jsonschema.net/ it shows "invalid value" when the number has more than one digit (e.g. '32', '10').

The value is saved anyway so it is a bit confusing but doesn't affect generating schema.

**Comment by jackwootton** [comment] 2018-10-02 20:17
This has been fixed in the new version (not yet released). Thanks for taking the time to report this. The problem was caused by html input patter being set to `[0-9]` rather than `^\d+$`.

**Comment by tloriato** [comment] 2019-11-12 11:46
I'm still receiving this error, it only works for single digit numbers right now.

**Comment by vstanchev** [comment] 2019-11-19 15:20
getting this as well, is it going to be released?

**Comment by jackwootton** [comment] 2020-03-01 17:18
The new version is now generally available; www.jsonschema.net

**Closed by jackwootton** 2020-03-01 17:18 UTC
Labels: bug
